---
# Source: cost-analyzer/charts/grafana/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: RELEASE-NAME-grafana
  labels:
    app: grafana
    chart: grafana-1.17.2
    release: RELEASE-NAME
    heritage: Helm
type: Opaque
data:
  admin-user: "YWRtaW4="
  admin-password: "bng3RDI3VmZ6TmNGU2hwRFBhZGljWW5uMVpNMlpzTUFSTzVFZHZNTg=="
  ldap-toml: ""
