---
# Source: cost-analyzer/templates/cost-analyzer-service-template.yaml
kind: Service
apiVersion: v1
metadata:
  name: RELEASE-NAME-cost-analyzer
  labels:
    
    app.kubernetes.io/name: cost-analyzer
    helm.sh/chart: cost-analyzer-1.48.0
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app: cost-analyzer
spec:
  selector:
    
    app.kubernetes.io/name: cost-analyzer
    app.kubernetes.io/instance: RELEASE-NAME
    app: cost-analyzer
  type: "ClusterIP"
  ports:
    - name: server
      port: 9001
      targetPort: 9001
    - name: model
      port: 9003
      targetPort: 9003
    - name: frontend
      port: 9090
      targetPort: 9090
