---
# Source: cost-analyzer/charts/prometheus/templates/pushgateway-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: "pushgateway"
    app: prometheus
    release: RELEASE-NAME
    chart: prometheus-8.15.0
    heritage: Helm
  name: RELEASE-NAME-prometheus-pushgateway
