---
# Source: cost-analyzer/charts/prometheus/templates/pushgateway-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: "pushgateway"
    app: prometheus
    release: RELEASE-NAME
    chart: prometheus-8.15.0
    heritage: Helm
  name: RELEASE-NAME-prometheus-pushgateway
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "2Gi"
