---
# Source: cost-analyzer/charts/prometheus/templates/pushgateway-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: "pushgateway"
    app: prometheus
    release: RELEASE-NAME
    chart: prometheus-8.15.0
    heritage: Helm
  name: RELEASE-NAME-prometheus-pushgateway
spec:
  selector:
    matchLabels:
      component: "pushgateway"
      app: prometheus
      release: RELEASE-NAME
  replicas: 1
  template:
    metadata:
      labels:
        component: "pushgateway"
        app: prometheus
        release: RELEASE-NAME
        chart: prometheus-8.15.0
        heritage: Helm
    spec:
      serviceAccountName: RELEASE-NAME-prometheus-pushgateway
      containers:
        - name: prometheus-pushgateway
          image: "prom/pushgateway:v0.8.0"
          imagePullPolicy: "IfNotPresent"
          args:
          ports:
            - containerPort: 9091
          readinessProbe:
            httpGet:
              path: /#/status
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
          resources:
            {}
          volumeMounts:
            - name: storage-volume
              mountPath: "/data"
              subPath: ""
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: RELEASE-NAME-prometheus-pushgateway
